/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bambu_nettuno;

import bd.bdriver;
import dispensador.SerialPort;
import dispensador.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import venta.venta;

/**
 *
 * @author Notebook
 */
public class principal extends javax.swing.JFrame {

    int resultado;
    int tipo;
    int cantidadFichas;
    static int value1;
    static int value2;
    static String operator;
    int totalapagar;
    ButtonGroup bgroup;
    ButtonGroup buttonGroup;
    int fichas;
    int dinero;
    ahorasi ahoraSi = new ahorasi();

    /**
     * Creates new form principal
     */
    public principal() {
        setUndecorated(true);
        initComponents();
        //this.set
        this.setLocationRelativeTo(null);
        //jPanel6.setOpaque(false);
        //panelpagar.setOpaque(false);
        txtFichasCantidad.setOpaque(false);

        bgroup = new ButtonGroup();
        //bgroup.add(buton1500);
        //bgroup.add(buton3000);
        //bgroup.add(buton5000);
        tipo = 1;

        buttonGroup = new ButtonGroup();
        ///buttonGroup.add(btnfichas);
        //btnfichas.setVisible(false);
        //buttonGroup.add(btnmanual);
        //btnmanual.setVisible(false);
        txtResult.setText("$ 0");
        //jLabel2.setVisible(false);
        ahoraSi.inicializarConexion();
        //ahoraSi.enviarDatos("2");
        setExtendedState(principal.MAXIMIZED_BOTH);
        //setExtendedState(jPanel1.set);
        dispose();
        //setUndecorated(true);
        //panelfichas.enable(false);
        //panelmanual.enable(false);
        //panelpagar.enable(false);
        //this.add(this);
        //this.pack();
        this.setExtendedState(this.getExtendedState() | principal.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btnMasFichas = new javax.swing.JLabel();
        btnMenosFichas = new javax.swing.JLabel();
        txtFichasCantidad = new javax.swing.JLabel();
        btnMasTicket = new javax.swing.JLabel();
        btnMenosTicket = new javax.swing.JLabel();
        txtManualCantidad = new javax.swing.JLabel();
        txtResult = new javax.swing.JLabel();
        btnpagar = new javax.swing.JLabel();
        btnborrar = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnClubNettuno = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 153, 255));
        setExtendedState(6);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(448, 3893, 0, 0);

        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(132, 3838, 70, 37);

        btnMasFichas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMasFichas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bambu_nettuno/mais.png"))); // NOI18N
        btnMasFichas.setText("+");
        btnMasFichas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMasFichas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMasFichasMouseClicked(evt);
            }
        });
        jPanel1.add(btnMasFichas);
        btnMasFichas.setBounds(460, 150, 110, 100);

        btnMenosFichas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMenosFichas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bambu_nettuno/menois.png"))); // NOI18N
        btnMenosFichas.setText("-");
        btnMenosFichas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnMenosFichas.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnMenosFichas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenosFichasMouseClicked(evt);
            }
        });
        jPanel1.add(btnMenosFichas);
        btnMenosFichas.setBounds(120, 150, 110, 100);
        btnMenosFichas.getAccessibleContext().setAccessibleDescription("");

        txtFichasCantidad.setFont(new java.awt.Font("Arial", 1, 75)); // NOI18N
        txtFichasCantidad.setForeground(new java.awt.Color(255, 255, 255));
        txtFichasCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtFichasCantidad.setText("0");
        jPanel1.add(txtFichasCantidad);
        txtFichasCantidad.setBounds(250, 110, 190, 180);

        btnMasTicket.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMasTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bambu_nettuno/mais.png"))); // NOI18N
        btnMasTicket.setText("+");
        btnMasTicket.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMasTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMasTicketMouseClicked(evt);
            }
        });
        jPanel1.add(btnMasTicket);
        btnMasTicket.setBounds(1130, 150, 120, 100);

        btnMenosTicket.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnMenosTicket.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bambu_nettuno/menois.png"))); // NOI18N
        btnMenosTicket.setText("-");
        btnMenosTicket.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMenosTicket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenosTicketMouseClicked(evt);
            }
        });
        jPanel1.add(btnMenosTicket);
        btnMenosTicket.setBounds(790, 150, 120, 100);

        txtManualCantidad.setFont(new java.awt.Font("Arial", 1, 75)); // NOI18N
        txtManualCantidad.setForeground(new java.awt.Color(255, 255, 255));
        txtManualCantidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtManualCantidad.setText("0");
        txtManualCantidad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(txtManualCantidad);
        txtManualCantidad.setBounds(920, 110, 190, 180);

        txtResult.setFont(new java.awt.Font("Arial", 1, 60)); // NOI18N
        txtResult.setForeground(new java.awt.Color(255, 255, 255));
        txtResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtResult.setText("0");
        jPanel1.add(txtResult);
        txtResult.setBounds(450, 530, 410, 90);

        btnpagar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnpagar.setForeground(new java.awt.Color(0, 204, 51));
        btnpagar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnpagar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bambu_nettuno/cash.png"))); // NOI18N
        btnpagar.setText("PAGAR");
        btnpagar.setCursor(new java.awt.Cursor(java.awt.Cursor.NE_RESIZE_CURSOR));
        btnpagar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnpagar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnpagar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnpagarMouseClicked(evt);
            }
        });
        jPanel1.add(btnpagar);
        btnpagar.setBounds(790, 530, 90, 120);

        btnborrar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnborrar.setForeground(new java.awt.Color(255, 0, 0));
        btnborrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnborrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bambu_nettuno/cancelarsolo.png"))); // NOI18N
        btnborrar.setText("CANCELAR");
        btnborrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnborrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnborrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnborrarMouseClicked(evt);
            }
        });
        jPanel1.add(btnborrar);
        btnborrar.setBounds(890, 530, 90, 140);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bambu_nettuno/FONDO4 copia.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(-6, 0, 1390, 720);

        btnClubNettuno.setBackground(new java.awt.Color(0, 0, 0));
        btnClubNettuno.setFont(new java.awt.Font("Tahoma", 3, 8)); // NOI18N
        btnClubNettuno.setForeground(new java.awt.Color(51, 153, 255));
        btnClubNettuno.setText("PROXIMAMENTE\nCLUB NETTUNO");
        btnClubNettuno.setEnabled(false);
        btnClubNettuno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClubNettunoMouseClicked(evt);
            }
        });
        btnClubNettuno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClubNettunoActionPerformed(evt);
            }
        });
        jPanel1.add(btnClubNettuno);
        btnClubNettuno.setBounds(1030, 610, 184, 44);
        jPanel1.add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 5, 5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClubNettunoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClubNettunoMouseClicked
        // TODO add your handling code here:
        totalapagar = Integer.parseInt(txtResult.getText()) * 50;
        cantidadFichas = Integer.parseInt(txtResult.getText());
        double totalconimpuesto = totalapagar;
        double totalsinimpuesto = totalapagar / 1.22;
        double montoimpuesto = totalapagar - totalsinimpuesto;
        String rut = null;
        int numeroTag = 0;
        venta venta = new venta(totalsinimpuesto, totalconimpuesto, montoimpuesto, cantidadFichas, rut, numeroTag, tipo);
        new verificaRut(venta).setVisible(true);

    }//GEN-LAST:event_btnClubNettunoMouseClicked

    private void btnpagarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnpagarMouseClicked
        // TODO add your handling code here:
        if (tipo == 1) {
            //totalapagar = Integer.parseInt(txtfichas.getText()) * 50;
            //cantidadFichas = Integer.parseInt(txtfichas.getText());
            double totalconimpuesto = totalapagar;
            double totalsinimpuesto = totalapagar / 1.22;
            double montoimpuesto = totalapagar - totalsinimpuesto;
            String rut = null;
            int numeroTag = 0;
            //TIPO 1 VENTA FICHAS
            //TIPO 2 VENTA CLUBNETTUNO
            //TIPO 3 VENTA MANUAL 
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "CONFIRMA LA COMPRA DE FICHAS POR $" + totalapagar + "?", "Warning", dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION) {
                // Saving code here
                //LLAMO POS
                ahoraSi.enviarDatos("A", txtFichasCantidad.getText());
                venta venta = new venta(totalsinimpuesto, totalconimpuesto, montoimpuesto, cantidadFichas, rut, numeroTag, tipo);
                //ARDUINO
                /*try {
                 //SerialPort.entregarFichas();
                 } catch (Exception e) {
                 System.out.println(e.getMessage());
                 JOptionPane.showMessageDialog(null, "OCURRIÓ UN ERROR :( ");

                 }*/
                try {
                    venta.insertarVenta(venta);
                } catch (SQLException ex) {
                    System.out.println("error");
                }
            }
            if (dialogResult == JOptionPane.NO_OPTION) {
                // Saving code here
            }

            //new confirmarcompra(totalapagar).setVisible(true);
            txtFichasCantidad.setText("0");
            txtResult.setText("$ 0");
            txtManualCantidad.setText("0");
        } else if (tipo == 2) {

        } else if (tipo == 3) {
            double totalconimpuesto = totalapagar;
            double totalsinimpuesto = totalapagar / 1.22;
            double montoimpuesto = totalapagar - totalsinimpuesto;

            String rut = null;
            int numeroTag = 0;
            //TIPO 1 VENTA FICHAS
            //TIPO 2 VENTA CLUBNETTUNO
            //TIPO 3 VENTA MANUAL 
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(null, "CONFIRMA LA COMPRA POR $" + totalapagar + "?", "Warning", dialogButton);
            if (dialogResult == JOptionPane.YES_OPTION) {
                // Saving code here
                //LLAMO POS
                venta venta = new venta(totalsinimpuesto, totalconimpuesto, montoimpuesto, cantidadFichas, rut, numeroTag, tipo);
                try {
                    venta.insertarVenta(venta);
                    JOptionPane.showMessageDialog(null, "VENTA CONFIRMADA! :) ");
                    txtResult.setText("$ 0");
                    //bgroup.clearSelection();
                    tipo = 1;
                    btnMasFichas.setVisible(true);
                    btnMenosFichas.setVisible(true);
                    btnMenosTicket.setVisible(true);
                    btnMasTicket.setVisible(true);

                } catch (SQLException ex) {
                    System.out.println("error");
                    JOptionPane.showMessageDialog(null, "OCURRIÓ UN ERROR :( ");
                    txtResult.setText("$ 0");
                    bgroup.clearSelection();
                    tipo = 1;

                }

            }
            if (dialogResult == JOptionPane.NO_OPTION) {
                txtFichasCantidad.setText("0");
                txtManualCantidad.setText("0");
                txtResult.setText("0");
                tipo = 0;
                btnMasFichas.setVisible(true);
                btnMenosFichas.setVisible(true);
                btnMenosTicket.setVisible(true);
                btnMasTicket.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnpagarMouseClicked

    private void btnMasFichasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasFichasMouseClicked
        // TODO add your handling code here:
        tipo = 1;
        if (txtFichasCantidad.getText().isEmpty() || txtFichasCantidad.getText().equals("0")) {
            txtFichasCantidad.setText("1");
            cantidadFichas = 1;
        } else {
            fichas = Integer.parseInt(txtFichasCantidad.getText());
            fichas++;
            txtFichasCantidad.setText(String.valueOf(fichas));
            cantidadFichas = 1;
        }
        totalapagar = Integer.parseInt(txtFichasCantidad.getText()) * 50;
        txtResult.setText("$ " + String.valueOf(totalapagar));
        btnMasFichas.setVisible(true);
        btnMenosFichas.setVisible(true);
        btnMasTicket.setVisible(false);
        btnMenosTicket.setVisible(false);
    }//GEN-LAST:event_btnMasFichasMouseClicked

    private void btnMenosFichasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenosFichasMouseClicked
        // TODO add your handling code here:
        tipo = 1;
        if (txtFichasCantidad.getText().isEmpty() || txtFichasCantidad.getText().equals("0")) {
            txtFichasCantidad.setText("1");
            cantidadFichas = 1;
        } else {
            fichas = Integer.parseInt(txtFichasCantidad.getText());
            fichas--;
            txtFichasCantidad.setText(String.valueOf(fichas));

            cantidadFichas = 1;
        }
        totalapagar = Integer.parseInt(txtFichasCantidad.getText()) * 50;
        txtResult.setText("$ " + String.valueOf(totalapagar));
        btnMasFichas.setVisible(true);
        btnMenosFichas.setVisible(true);
        btnMasTicket.setVisible(false);
        btnMenosTicket.setVisible(false);
    }//GEN-LAST:event_btnMenosFichasMouseClicked

    private void btnMasTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMasTicketMouseClicked
        // TODO add your handling code here:
        tipo = 3;
        if (txtManualCantidad.getText().isEmpty() || txtManualCantidad.getText().equals("0")) {
            txtManualCantidad.setText("50");
            cantidadFichas = 1;
        } else {
            dinero = Integer.parseInt(txtManualCantidad.getText()) + 50;
            //dinero+50;
            txtManualCantidad.setText(String.valueOf(dinero));
            cantidadFichas = 1;
        }
        totalapagar = Integer.parseInt(txtManualCantidad.getText());
        txtResult.setText("$ " + String.valueOf(totalapagar));
        btnMasFichas.setVisible(false);
        btnMenosFichas.setVisible(false);
        btnMasTicket.setVisible(true);
        btnMenosTicket.setVisible(true);

    }//GEN-LAST:event_btnMasTicketMouseClicked

    private void btnMenosTicketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenosTicketMouseClicked
        // TODO add your handling code here:
        tipo = 3;
        if (txtManualCantidad.getText().isEmpty() || txtManualCantidad.getText().equals("0")) {
            txtManualCantidad.setText("50");
            cantidadFichas = 1;
        } else {
            dinero = Integer.parseInt(txtManualCantidad.getText()) - 50;
            //dinero+50;
            txtManualCantidad.setText(String.valueOf(dinero));
            cantidadFichas = 1;
        }
        totalapagar = Integer.parseInt(txtManualCantidad.getText());
        txtResult.setText("$ " + String.valueOf(totalapagar));
        btnMasFichas.setVisible(false);
        btnMenosFichas.setVisible(false);
        btnMasTicket.setVisible(true);
        btnMenosTicket.setVisible(true);
    }//GEN-LAST:event_btnMenosTicketMouseClicked

    private void btnClubNettunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClubNettunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClubNettunoActionPerformed

    private void btnborrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnborrarMouseClicked
        // TODO add your handling code here:
        txtFichasCantidad.setText("0");
        txtManualCantidad.setText("0");
        txtResult.setText("0");
        tipo = 0;
        btnMasFichas.setVisible(true);
        btnMenosFichas.setVisible(true);
        btnMenosTicket.setVisible(true);
        btnMasTicket.setVisible(true);
    }//GEN-LAST:event_btnborrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClubNettuno;
    private javax.swing.JLabel btnMasFichas;
    private javax.swing.JLabel btnMasTicket;
    private javax.swing.JLabel btnMenosFichas;
    private javax.swing.JLabel btnMenosTicket;
    private javax.swing.JLabel btnborrar;
    private javax.swing.JLabel btnpagar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel txtFichasCantidad;
    private javax.swing.JLabel txtManualCantidad;
    private javax.swing.JLabel txtResult;
    // End of variables declaration//GEN-END:variables
}
